version: '2'

services:

  bootstrap:
    image: holochain/holochain-proto:develop
    ports:
      - "3142:3142"
    command: bs

  clutter1:
    image: holochain/holochain-proto:develop
    ports:
      - "3141:3141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/pyclutter"
    command: bash -c "cd /pyclutter; HCLOG_DHT_ENABLE=1 hcdev -DHTport=6001 -agentID=lucy -bootstrapServer=bootstrap:3142 -mdns=true web 3141"

  clutter2:
    image: holochain/holochain-proto:develop
    ports:
      - "4141:4141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/pyclutter"
    command: bash -c "cd /pyclutter; HCLOG_DHT_ENABLE=1 hcdev -DHTport=6002 -agentID=phil -bootstrapServer=bootstrap:3142 -mdns=true web 4141"

  clutter3:
    image: holochain/holochain-proto:develop
    ports:
      - "5141:5141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/pyclutter"
    command: bash -c "cd /pyclutter; HCLOG_DHT_ENABLE=1 hcdev -DHTport=6003 -agentID=clarence -bootstrapServer=bootstrap:3142 -mdns=true web 5141"
