import os
from time import sleep
from signal import SIGKILL
from paver.easy import *

@task
def build():
    for pyfile in path('src').files('*.py'):
        pyfile = path(pyfile)
        sh('transcrypt -n ' + pyfile.relpath())
        jsfile = path('src/__javascript__/' + pyfile.namebase + '.js')
        modfile = path(jsfile.relpath()[:-3] + '.mod.js')
        runtime = ['\n// Transcrypt runtime code for React']
        for line in jsfile.lines()[3:]:
            if line[1:2] == '(': break
            # patch bug in current Transcrypt runtime
            if line[12:37] == 'for (var attrib in obj) {':
                line = line[:31] + 'anObject' + line[34:]
            runtime.append(line)
        imports = [
           '// Autogenerated file do not edit',
           '\n// Imports for React']
        module = ['\n// Transcrypted Python module for React']
        for line in modfile.lines()[2:]:
            if line[2:12] == '__pragma__': break
            if line[2:9] == 'import ':
                imports.append(line[2:])
            else:
                module.append(line[2:])
        jsfile = path('src/' + pyfile.namebase + '.js')
        jsfile.write_lines(imports + runtime + module)
    # cleanup
    sh('for x in `find . -name "__javascript__"`; do rm -rf $x; done')
